# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
 
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
 
default_platform(:ios)
 
platform :ios do
desc "上传到测试版本到蒲公英"
  desc "生成本地版本"
  lane :topgyer do|option|
 
    #自动增加build
    increment_build_number
 
    #自动生成证书
cert
 
    #自动生成配置文件
#sigh(force: true)
#//我使用的是手动配置关闭这个。如需自动则打开即可
 
    #gym配置,打包输出。
 
    #fastlane gym --export_method ad-hoc
    #fastlane gym --export_method enterprise
    #fastlane gym --export_method app-store
    scheme_name = "Runner"
 
    #获取version和build版本号
    version = get_info_plist_value(path: "./#{scheme_name}/Info.plist", key: "CFBundleShortVersionString")
    build = get_info_plist_value(path: "./#{scheme_name}/Info.plist", key: "CFBundleVersion")
 
    #导出路径
    output_directory = "./build"
 
    #导出名称
    output_name = "#{scheme_name}_#{version}_#{build}_#{option[:desc]}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"
 
    gym(
  #  include_bitcode: "false",
    configuration:"Release",
    export_method: "app-store",     #这里填写导出方式，我使用的是development
    export_xcargs: "-allowProvisioningUpdates",
    scheme: scheme_name,
    clean: true,
    output_directory: output_directory,
    output_name: output_name
     )
  #使用自动证书管理
   enable_automatic_code_signing
 
#    pgyer(api_key: "044eb9f16f9c220a5ea42f4e1cb181b7", user_key: "b115d8662287dc297594178c6db2a7b1", update_description: "#{option[:desc]}")
end
end
